name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'master'
      release_name:
        description: 'Name of the release'
        required: true
        default: 'Test Release'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            target-name: x86_64-linux
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            target-name: aarch64-linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            target-name: x86_64-windows
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            target-name: aarch64-windows
          - os: macos-latest
            target: x86_64-apple-darwin
            target-name: x86_64-macos
          - os: macos-latest
            target: aarch64-apple-darwin
            target-name: aarch64-macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Set up MSVC for Windows builds
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: ${{ github.workspace }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target-name }}
          path: target/release/my_project

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ format('{0} {1}', github.event.inputs.release_name || 'Release', github.ref_name) }}
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ matrix.target-name }}.zip
          asset_name: ${{ matrix.target-name }}.zip
          asset_content_type: application/zip

